server:
  port: 1703
  servlet:
    context-path: /smas
spring:
  application:
    name: school-management-system
  mail:
    host: smtp.gmail.com
    port: 465
    username: ngynanhtai2105@gmail.com
    password: 123456baytam9
  datasource:
#    url: jdbc:postgresql://localhost:5432/school-management
#    username: postgres
#    password: 123456
    url: jdbc:postgresql://127.0.0.1:5432/school-management
    username: vnbgiangxd
    password: 0001
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      pool-name: MyHdsPool
      auto-commit: false
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  file:
    path: logs
    name: ${logging.file.path}/server.log
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
  level:
    root: INFO
    org:
      springframework: WARN
tls:
  company-a:
    instance: PKCS12
    resource: D:/Documents/HDBank/company_a.pkcs12
    protocol: TLS
    password: password
  company-b:
    instance: PKCS12
    resource: D:/Documents/HDBank/company_b.pkcs12
    protocol: TLS
    password: password
storage:
#  upload-folder: D:/Study/documents
  upload-folder: ../../documents
  delete-after-days: 30
schedule:
  document:
    delete-overdue:
      cron: 0 0 1 * * *
      config:
        overdue-days: 30
jwt:
  secret: ngynanhtai
  access-expiration-ms: 1800000
  refresh-expiration-ms: 3600000